name: Download Debian ISO

on:
  push:
    branches:
      - main
      - 3-debian

jobs:
  download_iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: Run Go Program to Get Debian ISO URL
        id: get_url
        working-directory: ./debian
        run: go run main.go

      - name: Download Debian ISO using wget
        run: wget ${{ env.download_url }}
