name: 'Ubuntu Server ISOs'
on:
  push:
  workflow_dispatch: # Manual trigger.

jobs:
  get-ubuntu-isos:
    name: 'Generate Matrix Ubuntu ISOs'
    runs-on: ubuntu-latest
    container:
      image: python:latest
    outputs:
      matrix: ${{ steps.iso.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Upgrade Pip
        run: |
          pip3 install --upgrade pip

      - name: Generate Matrix
        id: iso
        working-directory: ./ubuntu
        run: |
          pip3 install -q -r requirements.txt
          python3 isos.py

  download-ubuntu-isos:
    name: 'Download ${{ matrix.job.codename }}:${{ matrix.job.version }}'
    runs-on: self-hosted
    needs: get-ubuntu-isos
    strategy:
      matrix:
        job: ${{ fromJson(needs.get-ubuntu-isos.outputs.matrix) }}

    steps:
      - name: Download Ubuntu Server ISO
        run: |
          echo "Downloading latest: ${{ matrix.job.codename }}:${{ matrix.job.version }}"
          wget -q ${{ matrix.job.download_url }} -O ubuntu-server-${{ matrix.job.version }}-latest.iso

      - name: Latest Ubuntu Server ISO -> NAS
        run: |
          apt update -q
          apt install sshpass -y
          sshpass -p "${{ secrets.NAS_PASSWORD }}" scp -o StrictHostKeyChecking=no ./ubuntu-server-${{ matrix.job.version }}-latest.iso ${{ secrets.NAS_USERNAME }}@${{ secrets.NAS_IP}}:${{ secrets.NAS_ISO_PATH }}ubuntu-latest.iso

      - name: Delete ISO
        run: |
          rm ubuntu-server-${{ matrix.job.version }}-latest.iso
