name: 'Ubuntu Desktop ISOs'

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger.
  schedule:
    - cron: '0 0 * * MON' # Every Monday.

jobs:
  get-ubuntu-isos:
    name: 'Generate Matrix Ubuntu ISOs'
    runs-on: ubuntu-latest
    container:
      image: python:latest
    outputs:
      matrix: ${{ steps.iso.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Upgrade Pip
        run: |
          pip3 install --upgrade pip

      - name: Generate Matrix
        id: iso
        working-directory: ./ubuntu
        run: |
          pip3 install -q -r requirements.txt
          python3 metadata.py
        env:
          UBUNTU_SKU: 'desktop'

  download-ubuntu-isos:
    name: 'Download ${{ matrix.job.codename }}:${{ matrix.job.version }} - ${{ matrix.job.sku }}'
    runs-on: self-hosted
    needs: get-ubuntu-isos
    strategy:
      matrix:
        job: ${{ fromJson(needs.get-ubuntu-isos.outputs.matrix) }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: Download Ubuntu Desktop ISO
        run: |
          echo "Downloading latest: ${{ matrix.job.codename }}:${{ matrix.job.version }}"
          wget -q ${{ matrix.job.download_url }}
        # wget -q ${{ matrix.job.download_url }} -O ubuntu-server-${{ matrix.job.version }}-latest.iso

      - name: Download Ubuntu Desktop SHA256SUMS
        run: |
          wget "https://releases.ubuntu.com/${{ matrix.job.codename }}/SHA256SUMS"

      - name: Re-write SHA File
        working-directory: ./ubuntu
        run: |
          python3 checksum.py

      - name: Verify SHA of ISO
        run: |
          sha256sum -c SHA256SUMS
        # shasum -c - || exit 1

      - name: Latest Ubuntu Desktop ISO -> NAS
        run: |
          mv *.iso ubuntu-${{ matrix.job.sku }}-${{ matrix.job.version }}-latest.iso
          sshpass -p "${{ secrets.NAS_PASSWORD }}" scp -o StrictHostKeyChecking=no ./ubuntu-${{ matrix.job.sku }}-${{ matrix.job.version }}-latest.iso ${{ secrets.NAS_USERNAME }}@${{ secrets.NAS_IP}}:${{ secrets.NAS_ISO_PATH }}ubuntu-${{ matrix.job.sku }}-${{ matrix.job.version }}-latest.iso

      - name: Delete Files
        run: |
          rm ubuntu-${{ matrix.job.sku }}-${{ matrix.job.version }}-latest.iso
          rm SHA256SUMS

      - name: Build Notification
        uses: zchryr/build-notifier-action@v1.0.11
        with:
          body: ${{ toJson(matrix.job) }}
          url: ${{ secrets.WEBHOOK }}
          response_code: 201
          repo: ${{ github.repository }}
          workflow: $WORKFLOW
        env:
          WORKFLOW: ${{ github.workflow }}
