name: 'Virtio ISO'

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger.
  schedule:
    - cron: '0 0 * * MON' # Every Monday.

jobs:
  download-virtio-iso:
    name: 'Download Latest Virtio ISO'
    runs-on: self-hosted

    steps:
      - name: Download Virtio ISO
        run: |
          wget "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win.iso"

      - name: Latest Virtio ISO -> NAS
        run: |
          sshpass -p "${{ secrets.NAS_PASSWORD }}" scp -o StrictHostKeyChecking=no "virtio-win.iso" ${{ secrets.NAS_USERNAME }}@${{ secrets.NAS_IP}}:${{ secrets.NAS_ISO_PATH }}"virtio-win-latest.iso"

      - name: Create JSON Object
        run: |
          echo JSON="{\"virtio\":\"true\"}" >> $GITHUB_ENV

      - name: Build Notification
        uses: zchryr/notifier@main
        with:
          input: ${{ env.JSON }}
          url: '${{ secrets.WEBHOOK }}'
          response_code: '201'

      - name: Clean Workspace
        if: always()
        run: |
          rm -rf *
